package com.izbicki.jakub.error;


public interface ErrorCodes {

    String MOVIES_NOT_AVAILABLE = "MOVIES_NOT_AVAILABLE";
    String MOVIES_NOT_AVAILABLE_USER = "MOVIES_NOT_AVAILABLE_USER";
    String MAX_RENT_EXC = "MAX_RENT_EXC";
    String MAX_RENT_EXC_USER = "MAX_RENT_EXC_USER";
    String UNAVAILABLE_LOGIN = "UNAVAILABLE_LOGIN";
    String UNAVAILABLE_LOGIN_USER = "UNAVAILABLE_LOGIN_USER";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String USER_NOT_FOUND_USER = "USER_NOT_FOUND_USER";
    String MOVIES_NOT_RENTED = "MOVIES_NOT_RENTED";
    String MOVIES_NOT_RENTED_USER = "MOVIES_NOT_RENTED_USER";
    String MOVIES_NOT_FOUND = "MOVIES_NOT_FOUND";
    String MOVIES_NOT_FOUND_USER = "MOVIES_NOT_FOUND_USER";
    String BAD_MOVIE_ENUM = "BAD_MOVIE_ENUM";
    String BAD_MOVIE_ENUM_USER = "BAD_MOVIE_ENUM";
    String BAD_PAGE_PARAM = "BAD_PAGE_PARAM";
    String BAD_PAGE_PARAM_USER = "BAD_PAGE_PARAM_USER";
}
